version: "3"

networks:
  backbone:
    external:
      name: backbone

services:
  # https://github.com/scality/cloudserver
  s3:
    image: zenko/cloudserver:latest
    networks:
      - backbone
    volumes:
      - $PWD/data/s3:/data
      - $PWD/config/s3/config.json:/usr/src/app/config.json
    environment:
      - VIRTUAL_HOST=~^(|[a-z0-9]+\.)s3.aws.develop
      - VIRTUAL_PORT=8000
      - S3DATAPATH=/data
      - REMOTE_MANAGEMENT_DISABLE=1

  dynamodb:
    image: amazon/dynamodb-local
    networks:
      - backbone
    environment:
      - VIRTUAL_HOST=dynamodb.aws.develop
      - VIRTUAL_PORT=8000

  # https://github.com/airdock-io/docker-fake-sns
  sns:
    image: airdock/fake-sns
    networks:
      - backbone
    volumes:
      - $PWD/data/sns:/srv/ruby/fake-sns
    environment:
      - VIRTUAL_HOST=~^sns.([a-z0-9\-]+).aws.develop
      - VIRTUAL_PORT=9292

  # https://github.com/softwaremill/elasticmq
  sqs:
    image: softwaremill/elasticmq-native
    ports:
      - 9324
    networks:
      - backbone
    environment:
      - VIRTUAL_HOST=~^sqs.([a-z0-9\-]+).aws.develop
      - VIRTUAL_PORT=9324

  # TODO: https://github.com/lambci/docker-lambda
  # TODO: https://medium.com/albert-franzi/accessing-s3-data-through-sql-with-presto-ddb6d4fbb99c


