version: "3"

networks:
  fakews:
      name: ${FAKEWS_NETWORK:-fakews}

services:
  console:
    image: christhomas/fakews-console:latest
    build:
      context: console
      dockerfile: Dockerfile
    depends_on:
      - console-api
    networks:
      - fakews
    environment:
      - VIRTUAL_HOST=console.aws.develop
      - CONSOLE_API=http://console-api.aws.develop

  console-api:
    image: christhomas/fakews-console-api:latest
    build:
      context: console-api
      dockerfile: Dockerfile
    networks:
      - fakews
    environment:
      - VIRTUAL_HOST=console-api.aws.develop

  # https://github.com/scality/cloudserver
  s3:
    image: zenko/cloudserver:latest
    networks:
      - fakews
    volumes:
      - $PWD/data/s3:/data
      - $PWD/config/s3/config.json:/usr/src/app/config.json
    environment:
      - VIRTUAL_HOST=~^(|[a-z0-9]+\.)s3.(eu|us|ap)-(east|west|central)-(1|2).aws.develop
      - VIRTUAL_PORT=8000
      - S3DATAPATH=/data
      - REMOTE_MANAGEMENT_DISABLE=1
      - SCALITY_ACCESS_KEY_ID=mock
      - SCALITY_SECRET_ACCESS_KEY=mock

  # https://hub.docker.com/r/amazon/dynamodb-local/
  dynamodb:
    image: amazon/dynamodb-local
    networks:
      - fakews
    environment:
      - VIRTUAL_HOST=~^dynamodb.(eu|us|ap)-(east|west|central)-(1|2).aws.develop
      - VIRTUAL_PORT=8000

  # https://github.com/s12v/sns
  sns:
    image: s12v/sns
    networks:
      - fakews
    volumes:
      - $PWD/data/sns:/etc/sns
    environment:
      - VIRTUAL_HOST=~^sns.(eu|us|ap)-(east|west|central)-(1|2).aws.develop
      - VIRTUAL_PORT=9911

  # https://github.com/softwaremill/elasticmq
  sqs:
    image: softwaremill/elasticmq:latest
    networks:
      - fakews
    volumes:
      - $PWD/config/sqs/custom.conf:/opt/elasticmq.conf
    environment:
      - QUEUE_HOST=~^sqs.eu-west-1.aws.develop
      - VIRTUAL_HOST=~^sqs.(eu|us|ap)-(east|west|central)-(1|2).aws.develop
      - VIRTUAL_PORT=9324

#  sqs-experimental:
#    image: softwaremill/elasticmq-native:latest
#    networks:
#      - backbone
#    volumes:
#      - $PWD/config/sqs/custom.conf:/opt/elasticmq.conf
#    environment:
#      - QUEUE_HOST=sqs.eu-central-1.aws.develop
#      - VIRTUAL_HOST=~^sqs.(eu|us|ap)-(east|west|central)-(1|2).aws.develop
#      - VIRTUAL_PORT=9324

  # https://github.com/picadoh/motocker
  iam:
    image: picadoh/motocker:latest
    networks:
      - fakews
    environment:
      - VIRTUAL_HOST=~^iam.(eu|us|ap)-(east|west|central)-(1|2).aws.develop
      - VIRTUAL_PORT=5000
      - MOTO_SERVICE=iam


  # https://github.com/picadoh/motocker
  cloudwatch:
    image: christhomas/motocker:latest
    networks:
      - fakews
    environment:
      - VIRTUAL_HOST=~^logs.(eu|us|ap)-(east|west|central)-(1|2).aws.develop
      - VIRTUAL_PORT=5000
      - MOTO_SERVICE=cloudwatch

  # TODO: https://github.com/lambci/docker-lambda
  # TODO: https://medium.com/albert-franzi/accessing-s3-data-through-sql-with-presto-ddb6d4fbb99c
